name:                cleaner

dependencies:
- base >= 4.7 && < 5
- text
- kanji

default-extensions:
- OverloadedStrings

library:
  source-dirs: src

executables:
  kek-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cleaner